;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	back-to-indentation-or-beginning
	backward-kill-word-or-kill-region
	mark-sexp
	skeleton-pair-insert-maybe
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-mode
	beginning-of-buffer
	smex
	))
