;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        backward-kill-word-or-kill-region
        c-electric-slash
        electric-newline-and-maybe-indent
        indent-for-tab-command
        mark-sexp
        max/eclipse-search-selected-region
        org-self-insert-command
        py-electric-colon
        skeleton-pair-insert-maybe
        toggle-input-method
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        beginning-of-buffer
        end-of-buffer
        helm-confirm-and-exit-minibuffer
        smex
        ))
